name: Pulumi Preview
on:
  - pull_request

defaults:
  run:
    working-directory: infrastructure

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi dependencies
        run: npm install

      - name: Pulumi Preview
        uses: pulumi/actions@v6
        with:
          work-dir: ./infrastructure
          command: preview
          stack-name: artemmatiushenko1-org/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
